version: '3'
services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: docker/php
    container_name: php
    volumes:
      - .:/app

  composer:
    image: composer:1.10
    container_name: composer
    volumes:
      - .:/app
    command: bash -c "composer install && tail -f /dev/null"
